### ISSUE TITLE
redirect_uri_mismatch

### ISSUE THREAD

**Issue by vj68** [miss-invincible/codechef-sample-app#1]
Hello Miss Invincible.

Upon running the codechef sample app as instructed,
this error is reported. 

{"error":"redirect_uri_mismatch","error_description":"The redirect URI provided is missing or does not match","error_uri":"http:\/\/tools.ietf.org\/html\/rfc6749#section-3.1.2"}

**Comment by Pratims10** [comment]
Hello rajvijay68,
I am facing exactly the same issue. Did you figure out the problem and solved it? If so, kindly help me.

**Comment by sgcrafted** [comment]
@rajvijay68 @Pratims10 could you share the details that you are filling like redirect uri?

**Comment by Pratims10** [comment]
That was the issue. It is working fine now. Thanks

**Comment by shim1998** [comment]
Hello having the same issue 
redirect uri is http://localhost:8000

**Comment by namanjain007** [comment]
Hello @miss-invincible , can we code our whole app in React ?

**Comment by sgcrafted** [comment]
> Hello @miss-invincible , can we code our whole app in React ?

@namanjain007 please check with CodeChef for this. I am not sure about it.

**Comment by pulkitm** [comment]
After Giving permissions , only a blank page opens.
Is this intended or some error on my side?

**Comment by lm10-piyush** [comment]
@miss-invincible  $result = $response['result']['data']; in index.php this gives me error, how to fix it?
I just replace cliend_id and cliend_secret 
error msg:   **Notice: Trying to access array offset on value of type null in**
I have checked it, it is giving problem from make_curl_request
Yeah It ran via Xampp, not by php -S localhost:8000

**Comment by himpat29** [comment]
@rajvijay68 @Pratims10 @miss-invincible I am facing the same issue. Please tell what to give in redirect url.

**Comment by lm10-piyush** [comment]
> @rajvijay68 @Pratims10 @miss-invincible I am facing the same issue. Please tell what to give in redirect URL.

redirect URL used is xampp link. example: https:localhost/test/index.php 
I used same link for the app link and redirect link. remember redirect link must be same as in you registered on CodeChef and in index.php.
I hope it helps if any issue you can ping me again.
